upstream frontend_up {
    server frontend:3000;
}

server {
    listen 80;
    listen [::]:80;
    server_name alfaofc.com.br www.alfaofc.com.br;

    # redireciona tudo pra HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name alfaofc.com.br www.alfaofc.com.br;

    ssl_certificate     /etc/ssl/certs/alfaofc_fullchain.pem;
    ssl_certificate_key /etc/ssl/private/alfaofc_privkey.pem;

    client_max_body_size 10M;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://frontend_up;
    }

    location ~* ^/_next/static/ {
        proxy_pass http://frontend_up;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location ~* ^/_next/image/ {
        proxy_pass http://frontend_up;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}
